// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAaN7JjNKt0cyZLetqFAlUSYlHL5JO-Sk',
    appId: '1:428014561284:android:8c11a98986c46179a36d51',
    messagingSenderId: '428014561284',
    projectId: 'frotadev-7f775',
    databaseURL: 'https://frotadev-7f775.firebaseio.com',
    storageBucket: 'frotadev-7f775.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2lP_CTgIqn0pcc1wrZjHwinxk_AlQWU8',
    appId: '1:428014561284:ios:3ac1a0511d16c9a7a36d51',
    messagingSenderId: '428014561284',
    projectId: 'frotadev-7f775',
    databaseURL: 'https://frotadev-7f775.firebaseio.com',
    storageBucket: 'frotadev-7f775.appspot.com',
    androidClientId: '428014561284-5a8g5de93oi9rh0sr3kimsim7ekrd8ov.apps.googleusercontent.com',
    iosClientId: '428014561284-0454j0t3pbfp8q5f5bun2o222aj6uf2e.apps.googleusercontent.com',
    iosBundleId: 'com.example.pocAutenticacaoFlutterFire',
  );
}
